settings:
  
  timeStep: 1000.0
  simTime: 15.0

  motors: {
    "ascent": "e12",
  }

  max_motor_ignition_delay: 0.78

  gyroSpeed: 500
  accelSpeed: 500
  gpsSpeed: 10
  baroSpeed: 40

  rocket_mass: 0.81

  mmoi: [0.0502, 0.0548202733120976, 0.0548202733120976]

  cp_location: [-0.4, 0.0, 0.0]
  tvc_location: [0.4, 0.0, 0.0]
  
  drag_area: 0.05
  drag_coeff: 0.05

  wind_speed: [0.0, 0.0, 0.0]

  # y and z
  max_tvc_angle: [5.0, 5.0]
  tvc_noise: 0.0

  tvc_servo_speed: 250
  tvc_linkage_ratio: 4