settings:
  
  timeStep: 1000.0
  simTime: 60.0

  motors: {
    "ascent": "d12",
  }

  max_motor_ignition_delay: 0.78

  gyroSpeed: 500
  accelSpeed: 500
  gpsSpeed: 10
  baroSpeed: 40

  rocket_mass: 0.81

  mmoi: [0.0, 0.0, 0.0]

  cp_location: [0.0, 0.0, 0.0]
  
  drag_area: 0.0
  drag_coeff: 0.0

  wind_speed: [0.0, 0.0, 0.0]

  # y and z
  max_tvc_angle: [0.0, 0.0]
  tvc_noise: 0.0

  tvc_servo_speed: 250
  tvc_linkage_ratio: 4