settings:

  timeStep: 1000.0
  simTime: 180.0

  # motor types:

  # motors/AeroTech_H13ST.rse
  # motors/Apogee_F10.rse
  # motors/Estes_F15.rse
  # motors/Estes_E12.rse
  # motors/Estes_D12.rse
  # motors/Estes_C6.rse
  

  motors: {
    "ascent" : "motors/Estes_D12.rse"
  }

  max_motor_ignition_delay: 0.78

  gyroSpeed: 500
  accelSpeed: 500
  gpsSpeed: 10
  baroSpeed: 40

  rocket_mass: 0.8

  mmoi: [0.0502, 0.0502, 0.0502]

  cp_location: [-0.4, 0.0, 0.0]
  tvc_location: [0.454, 0.0, 0.0]

  drag_area_sideways: 0.283
  drag_area_nose: 0.026
  drag_coeff: 0.55

  wind_speed: [0.0, 0.05, 0.1]

  # y and z
  max_tvc_angle: [6.0, 6.0]
  tvc_noise: 0.0

  tvc_servo_speed: 250
  tvc_linkage_ratio: 4

  real_time: False